     # /*********************** Landing / Main ********************/

platon_main_landing:
    path: /
    controller: App\Controller\LandingController::index

platon_main_home:
    path: /home
    controller: App\Controller\LandingController::home


    # /*********************** Log ********************/
platon_login:
    path: /login
    controller: App\Controller\SecurityController::login

platon_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout




    # /*********************** HowTo ********************/

platon_howto_main:
    path : /how/to
    controller : App\Controller\HowToController::index





    # /*********************** Catalogue ********************/

platon_catalogue_index:
    path : /catalog
    controller : App\Controller\CatalogueController::index

platon_catalogue_new:
    path : /catalog/new
    controller : App\Controller\CatalogueController::new

platon_catalogue_show:
    path : /catalog/{id}
    controller : App\Controller\CatalogueController::show

platon_catalogue_edit:
    path : /catalog/{id}/edit
    controller : App\Controller\CatalogueController::edit

platon_catalogue_delete:
    path : /catalog/{id}/delete
    controller : App\Controller\CatalogueController::delete


 # /*********************** Subcategorie ********************/

platon_subcategories_show:
    path : /sub/categories/{id}
    controller : App\Controller\SubCategoriesController::show




# /*********************** User ********************/

platon_user_index:
    path : /user
    controller : App\Controller\UserController::index

platon_user_new:
    path : /user/new
    controller : App\Controller\UserController::new

platon_user_show:
    path : /user/{id}
    controller : App\Controller\UserController::show

platon_user_edit:
    path : /user/{id}/edit
    controller : App\Controller\UserController::edit

platon_user_delete:
    path : /user/{id}/delete
    controller : App\Controller\UserController::delete

    # /*********************** Ticket ********************/
platon_ticket_remove:
    path: /ticket/remove/{idTicket}
    controller: App\Controller\LandingController::removeTicket

platon_ticket_update:
    path: /ticket/update/{idTicket}
    controller: App\Controller\LandingController::finishClass

# On transmet l'id du User dans l'url afin de le récupérer en tant que receiver dans le ticket
platon_ticket_create:
    path : /ticket/new/{user}
    controller : App\Controller\UserController::newTicket


    # /*********************** User ********************/
platon_favoris:
    path: /favoris/{user}
    controller : App\Controller\UserController::addFavorite




    # /*********************** registration ********************/

platon_register:
    path : /register
    controller : App\Controller\RegistrationController::register


######################################################################
#                            Pages Statiques                        #
#####################################################################
platon_quisommesnous:
    path: /qui-sommes-nous
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: 'statique/quisommesnous.html.twig'

platon_mentionslegales:
    path: /mentions-legales
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: 'statique/mentionslegales.html.twig'

platon_cgu:
    path: /cgu
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: 'statique/cgu.html.twig'

platon_contact:
    path: /contact
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: 'statique/contact.html.twig'

platon_informationslegales:
    path: /informations-legales
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: 'statique/informationslegales.html.twig'

platon_parametresdescookies:
    path: /parametresdescookies
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: 'statique/parametresdescookies.html.twig'

platon_lachartedeplaton:
    path: /lachartedeplaton
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: 'statique/lachartedeplaton.html.twig'





api_data:
    path: /api_data
    controller: App\Controller\Api©ontroller::getData

